### ISSUE TITLE
Issue when FS has a replica

### ISSUE THREAD

**Issue by sorentGH** [khibma/update-hosted-feature-service#13]
This tool is really great, thanks. 
However, if replicas exist for the service you are trying to overwrite, the tool fails. 
Either you'd have to locate the replicas and unregister them - or you'd have to delete the service and the sd file and create the Feature service again (with it's original name). 
Quite often sync is only used in these services to be able to take them offline on Collector app, but with no intention to do edits. 
Could the script be altered to take care of this scenario where replicas exist?
Best Regards

**Comment by khibma** [comment]
I dont have a lot of knowledge in the sync/replica area, so a question to you:
How would you handle this case, or expect it to be handled? 

- Force the delete (but doing so will be like starting fresh, so any apps that hold the itemID reference will break)

- Do some search to unregister replicas, and I guess after updating, turn them back on?

- Error message for this case, telling the person running the script about the problem and letting them take appropriate action

- other?

**Comment by sorentGH** [comment]
Kevin,

- For this case, where the Sync parameter is only used, because it has to be there to take the map offline, I think deleting and creating the service again with exactly the same name and settings will work fine. 
It's correct that the AGO element-ID and the service ItemId is changed, but the REST-URL remains the same and apparently this is all that the webmap needs to keep track of the layers. Meaning that you can drop the old offline map on your Collector app and take the new map offline. Note that this wont work if the plan is to edit the services data in the field, since the replica is gone.

- If it's possible to delete all the replicas on the service through a script and run this as the first part of the update service script, that could do the job nicely. I don't think you can reestablish the replicas afterwards, but not needed anyway since you're not going to edit data.

- An error message is better than nothing, but still the person would then have to do some manual tasks.

thanks,
Søren

**Comment by khibma** [comment]
After discussion, the proper thing to do is simply throw a message that sync has been enabled, replicas exist and **quit**. Its not correct to have the script simply destroy/ignore the existing replicas. 

This workflow replaces the entire data inside the service. This practice directly conflicts with edits/replicas workflow.  If sync + replicas are used in your environment this workflow doesn't really fit with that. This conflict needs of two competing workflows needs to be resolved outside this script. (ie. discussion within your organization with a plan on how you'll updating data moving forward with one of these workflows, not both)

**Comment by sorentGH** [comment]
Kevin,

Thanks for looking into this.
I agree it is not a good solution to just overwrite a service with replicas.
However that is what is needed in this particular case, so we’ll have to carry on with a manual workflow.

Rgds,
Søren
