### ISSUE TITLE
Uploading SD file fails if original is not in root folder of My Content

### ISSUE THREAD

**Issue by amarinelli** [khibma/update-hosted-feature-service#2]
The [Upload](https://github.com/khibma/update-hosted-feature-service/blob/master/update.py#L154-L181) function produces an error and the upload fails if the original Service Definition has been moved to a folder other than the root folder in My Content of ArcGIS Online.

If the SD is moved back to the root folder and the script is re-run, it will complete successfully.

Regardless of which folder the SD is in, the item will still be found by the script and the ID printed to the screen during execution.

```python
".sd file not uploaded. Check the errors and try again."

{u'error': {u'messageCode': u'CONT_0005', u'message': u'Item does not exist in this folder.', u'code': 400, u'details': []}}
```

**Comment by khibma** [comment]
Fixed by https://github.com/khibma/update-hosted-feature-service/pull/7
