### ISSUE TITLE
Enabling Sharing of the feature service fails if original is not in root folder of My Content

### ISSUE THREAD

**Issue by amarinelli** [khibma/update-hosted-feature-service#3]
The [enableSharing](https://github.com/khibma/update-hosted-feature-service/blob/master/update.py#L219-L236) function produces an error and fails if the original feature service has been moved to a folder other than the root folder in My Content of ArcGIS Online.

If the feature service is moved back to the root folder and the script is re-run, it will complete successfully.

Regardless of which folder the feature service is in, the item will still be found by the script and the ID printed to the screen during execution.

```python
"failed:"
{u'error': {u'messageCode': u'CONT_0005', u'message': u'Item does not exist in this folder.', u'code': 400, u'details': []}}
```

**Comment by tpcolson** [comment]
Is there any update on when this will be resolved?

**Comment by amarinelli** [comment]
See my [pull request](https://github.com/arcpy/update-hosted-feature-service/pull/5) on the arcpy repository which fixes this.

**Comment by tpcolson** [comment]
Since posting I have found that solution, and it works...

**Comment by khibma** [comment]
Fixed by https://github.com/khibma/update-hosted-feature-service/pull/7
